### ISSUE TITLE
Error when saving entry from console command

### ISSUE THREAD

**Issue by sjelfull** [aelvan/Preparse-Field-Craft#13]
If you try to save a entry that has a Preparse field, you will get this error:

```php
Exception: Property "Craft\ConsoleApp.session" is not defined. in /app/www/craft/app/framework/base/CComponent.php:130
Stack trace:
#0 /app/www/craft/app/framework/base/CModule.php(105): CComponent->__get('session')
#1 /app/www/craft/app/services/UserSessionService.php(1093): CModule->__get('session')
#2 /app/www/craft/app/framework/web/auth/CWebUser.php(668): Craft\UserSessionService->getState('Yii.CWebUser.fl...', NULL)
#3 /app/www/craft/app/framework/web/auth/CWebUser.php(699): CWebUser->getFlash('element-1890-pr...', NULL, false)
#4 /app/www/plugins/preparsefield/fieldtypes/PreparseField_PreparseFieldType.php(27): CWebUser->hasFlash('element-1890-pr...')
```

I think adding a couple craft()->isConsole() checks before using the craft()->userSession service (line 27 and ~58 in PreparseFieldType) works well.

**Comment by aelvan** [comment]
I see, so when running in the console there is no session at all? 

The problem with removing the references to craft()->userSession is that it's the stop-condition for the `saveElement`. If the session variable isn't set and checked, `onAfterElementSave` will result in an endless loop. Not sure how else to implement the stop-condition. Maybe with craft()->cache or something. Let me know if you have any ideas.

**Comment by bossanova808** [comment]
Any update on this one?  Is it jsut not possible to save entries with preparse fields at all?  Is it possible perhaps to create the user session in the console command?  (That may be a stupid question, I don't have any experience here!)

I want to save off 6 specific entries that are pulling in  some generated content from an ebook and when I update the book & re-build the epub etc, I'd like the Craft entries to update.  They pull in the content via Preparse, so it would just be a yiic console thing that triggers those 6 entries to re-save.

But if I can't save them via the command line I'll for now save myself the trouble of learning how to do a Craft console command! :)

**Comment by aelvan** [comment]
I think maybe @sjelfull tested a fix for that? I'll check with him and see if it's something that could be merged into the plugin.

**Comment by sjelfull** [comment]
@bossanova808 @aelvan This versions seems to work well for me. I haven't had time to test it extensively, though.
```
public function onAfterElementSave ()
    {
        $fieldHandle         = $this->model->handle;
        $fieldTwig           = $this->getSettings()->fieldTwig;
        $elementType         = $this->element->getElementType();
        $elementTemplateName = strtolower($elementType);
        $flashId             = 'element-' . $this->element->id . '-preparseField-' . $fieldHandle;
        $isConsole           = craft()->isConsole();

        if ( $isConsole && !PreparseFieldPlugin::hasRun($flashId) || !$isConsole && !craft()->userSession->hasFlash($flashId) ) { // only run if it hasn't already this session

            //PreparseFieldPlugin::log('Saving "' . $flashId, LogLevel::Info, $force = true);

            // Set generateTransformsBeforePageLoad = true
            $configService                    = craft()->config;
            $generateTransformsBeforePageLoad = $configService->get('generateTransformsBeforePageLoad');
            $configService->set('generateTransformsBeforePageLoad', true);

            // save cp template path and set to site templates
            if ( craft()->getBuild() < 2778 ) {
                $oldPath = craft()->path->getTemplatesPath();
                craft()->path->setTemplatesPath(craft()->path->getSiteTemplatesPath());
            }
            else {
                $oldMode = craft()->templates->getTemplateMode();
                craft()->templates->setTemplateMode(TemplateMode::Site);
            }

            // parse data
            $parsedData = craft()->templates->renderString($fieldTwig, array( $elementTemplateName => $this->element ));

            // restore cp template paths
            if ( craft()->getBuild() < 2778 ) {
                craft()->path->setTemplatesPath($oldPath);
            }
            else {
                craft()->templates->setTemplateMode($oldMode);
            }

            // save element, set flash indicating it has been saved
            $this->element->getContent()->setAttribute($fieldHandle, $parsedData);

            if ( !$isConsole ) {
                craft()->userSession->setFlash($flashId, "saved");
            }
            else {
                PreparseFieldPlugin::setRun($flashId);
            }

            $success = craft()->elements->saveElement($this->element);

            // if no success, log error
            if ( !$success ) {
                PreparseFieldPlugin::log('Couldn’t save element with id "' . $this->element->id . '" and preparse field "' . $fieldHandle . '"',
                    LogLevel::Error);
            }

            // Set generateTransformsBeforePageLoad back to whatever it was
            $configService->set('generateTransformsBeforePageLoad', $generateTransformsBeforePageLoad);
        } else {
            //PreparseFieldPlugin::log('Ignoring "' . $flashId, LogLevel::Info, $force = true);
        }
    }
```

**Comment by aelvan** [comment]
@bossanova808 Have you tested this?

**Comment by bossanova808** [comment]
Sorry folks, sick.  Will check it out later in the week.

**Comment by bossanova808** [comment]
Ok so I was planning to test the above, however it turns out I don't actually need it?  I began by trying to raise the same error but I'm not getting it - I have one pre-parse field on these entries that simply includes some html content in to a dummy field so that can then be indexed by Craft's search stuff.  

These entries are re-saved without the need for the above code...

I do have plans to write an console command to re-generate imager transforms on demand by re-saving assets with a pre-parse field that generates the transforms, so I may hit it then and will update you.  Not quite sure when I will get to that though.

I doubt it makes much difference but I am bootstrapping a specific craft environment to get my console runner to run properly using this:

```
<?php

/**
 * a front end for yiic.php that looks for env on cmdline and sets CRAFT_ENVIRONMENT
 * accordingly. I put this script in a folder called "utils" in the root of my website
 * install. So instead of doing something like
 *     php $root/craft/app/etc/console/yiic.php plugin cmd
 * you would call
 *     php $root/utils/yiic_frontend.php --env=envname plugin cmd
 * where "envname" is the config environment you wish to use.
 */

for ($i = 1; $i < count($_SERVER['argv']); $i++) {
    $arg = $_SERVER['argv'][$i];
    if (strpos($arg, '--env=') === 0) {
        $env = explode('=', $arg)[1];
        printf("---- setting env \"%s\"\n", $env);
        define('CRAFT_ENVIRONMENT', $env);
        array_splice($_SERVER['argv'], $i, 1);
        break;
    }
}

require(__DIR__ . '/../../craft/app/etc/console/yiic.php');
```
and my actual command is just as simple as it gets really:
```
<?php
namespace Craft;

class BusinessLogicCommand extends BaseCommand
{
    public function actionResaveFODEntries()
    {
        print("### Resaving entries for Fundamentals Of Digital\n(So search indexes are updated by causing PreParse to re-pull in the generated content).\n\n");
        
        $criteria = craft()->elements->getCriteria(ElementType::Entry);
        $criteria->section = 'fundamentalsOfDigital';
     

        foreach ($criteria as $entry)
        {
            $success = craft()->entries->saveEntry($entry);

            if (!$success)
            {
                print("Failed to save entry $entry->title\n");
            }        
            else
            {
                print("Saved $entry->title\n");
            }
        }


    }
}
```

**Comment by bossanova808** [comment]
Sorry I missed Carl's stuff above - looks like far greater minds are on it than mine!

**Comment by aelvan** [comment]
@bossanova808 @sjelfull Version 0.3.0 should have fixed the issue with saving from the console.
